name: List and Save GitHub Packages
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # Run daily
jobs:
  list-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List packages and write to file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export ORG='nmfs-opensci'
          echo "Listing container packages for the organization: $ORG"

          packages=$(gh api --paginate "/orgs/\"$ORG\"/packages?package_type=container" -q '.[] | .name + " " + .repository.name') || echo "Failed to retrieve packages"
          echo "$packages" > packages.txt
          cat packages.txt

          while IFS= read -r line; do
            package_name="${line%% *}"
            repo_name="${line#* }"
            echo "org: $ORG repo: $repo_name --> package name $package_name"

            versions=$(gh api --paginate "/orgs/\"$ORG\"/packages/container/${package_name}/versions" -q '.[] | .name' | sort -V) || echo "Failed to retrieve versions for $package_name"
            echo "$versions"
          done < packages.txt

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add packages.txt
          git commit -m "Updated package list for GitHub Page using GitHub CLI" || echo "No changes to commit"
          git push
